# We will implement 'AND' with the help of neural networks

### Forward Propagation without any hidden layer, and random weights

In [2]:
import numpy as np

In [5]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [6]:
def sig(z):
    return 1 / (1 + np.exp(-z))

In [7]:
weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.17490941],
        [ 0.31991164]]), array([0.1992712]))

In [8]:
output = np.dot(x,weights) + bias
output

array([[0.1992712 ],
       [0.51918284],
       [0.02436179],
       [0.34427343]])

### Lets try to add one hidden layer

In [9]:
wh = 2 * np.random.random((2,2)) - 1
bh = 2 * np.random.random((1,2)) - 1
wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [10]:
output0 = x
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.63068581],
       [0.63965116],
       [0.62475352],
       [0.63358389]])