In [1]:
import numpy as np

In [2]:
def fit(train_x, train_y):
    result = {}
    class_values = set(train_y)
    result['total_data'] = len(train_y)
    for current_class in class_values:
        result[current_class] = {}
        train_x_class = train_x[train_y == current_class]
        train_y_class = train_y[train_y == current_class]
        num_features = train_x.shape[1]
        result[current_class]['total_count'] = len(train_y_class)
        for feature in range(num_features):
            result[current_class][feature] = {}
            possible_values = set(train_x[:,feature])
            for current_value in possible_values:
                result[current_class][feature][current_value] = (train_x_class[:, feature] == current_value).sum()
    return result

In [3]:
def getProb(current_class, data_x, dictionary):
    ans = np.log(dictionary[current_class]['total_count']) - np.log(dictionary['total_data'])
    for feature in range(len(dictionary[current_class].keys()) - 1):
        feature_count = dictionary[current_class][feature][data_x[feature]] + 1
        class_count   = dictionary[current_class]['total_count'] + len(dictionary[current_class][feature].keys())
        ans += (np.log(feature_count) - np.log(cxxlass_count))
    return ans

In [4]:
def predictSinglePoint(data_x, dictionary):
    best_class = None
    best_prob = None
    first = True
    for current_class in dictionary.keys():
        if current_class == 'total_data':
            continue
        current_prob = getProb(current_class, data_x, dictionary)
        if first or current_prob > best_prob:
            best_prob = current_prob
            best_class = current_class
        first = False
    return best_class

In [5]:
def predict(test_x, dictionary):
    pred_y = []
    for data_x in test_x:
        pred_y.append(predictSinglePoint(data_x, dictionary))
    return np.array(pred_y)

# Implementing Naive Bayes on Iris Dataset

In [6]:
def makeLabelled(column):
    second_label = column.mean()
    first_label = 0.5 * column.mean()
    third_label = 1.5 * column.mean()
    
    for i in range(0, len(column)):
        if(column[i] < first_label):
            column[i] = 0
        elif(column[i] < second_label):
            column[i] = 1
        elif(column[i] < third_label):
            column[i] = 2
        else:
            column[i] = 3
    return column

In [7]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [8]:
for i in range(0, X.shape[1]):
    X[:,i] = makeLabelled(X[:,i])

In [9]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y, test_size = 0.25, random_state = 0)

In [10]:
dictionary = fit(X_train, Y_train)

In [11]:
Y_pred = predict(X_test, dictionary)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38

[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]
