In [1]:
import numpy as np

In [2]:
data = np.genfromtxt('training_boston_x_y_train.csv', delimiter = ',')
x = data[:,:-1]
y = data[:, -1]


from sklearn import preprocessing
sc = preprocessing.StandardScaler()
sc.fit(x)
x = sc.transform(x)

x,y,x.shape,y.shape

(array([[-0.40098068, -0.49042688, -1.28149216, ..., -0.32264241,
          0.42027996, -1.10095452],
        [-0.40053396, -0.49042688,  0.20753471, ...,  0.09391068,
          0.30257958, -0.53143278],
        [ 0.09900799, -0.49042688,  0.96425328, ...,  0.78816582,
         -3.72614514,  0.86057789],
        ...,
        [-0.40141319, -0.49042688,  0.20753471, ...,  0.09391068,
          0.34289385, -0.34758231],
        [-0.40357903, -0.49042688, -1.16949207, ..., -0.7391955 ,
          0.21589851, -0.75260628],
        [ 0.30324229, -0.49042688,  0.96425328, ...,  0.78816582,
          0.39790715, -1.35806871]]),
 array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
        20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
        33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
        17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
        13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
   

In [3]:
test_data = np.genfromtxt('test_boston_x_test.csv', delimiter = ',')
test_data = sc.transform(test_data)

In [4]:
def cost(x,y,m):
    final_cost = 0
    r = x.shape[0]
    c = x.shape[1]
    for i in range(r):
        ypred = 0
        for j in range(c):
            ypred += m[j] * x[i][j]
        final_cost += (1/r) * ((y[i] - ypred) ** 2)
    print(final_cost)
    
def gradientStep(x,y,coeff,alpha):
    rows = x.shape[0]
    features = x.shape[1]
    slope = [0 for i in range(features)]
    for i in range(rows):
        m_x = 0
        for j in range(features):
            m_x += coeff[j] * x[i,j]
        for j in range(features):
            slope[j] += (-2/rows) * (y[i] - m_x) * x[i][j]
    for j in range(features):
        coeff[j] -= alpha * slope[j]
    
def gradientDescent(x,y,alpha,itr):
    x = np.append(x, np.ones((x.shape[0], 1)), axis = 1)
    rows = x.shape[0]
    features = x.shape[1]
    coeff = [0 for i in range(features)]
    for _itr in range(itr):
        gradientStep(x,y,coeff,alpha)
        cost(x,y,coeff)
    return coeff

In [5]:
m = gradientDescent(x,y,0.1,500)
m

372.6402282491625
246.08068449886875
166.3146252952613
115.5014638404627
83.05871412434605
62.30835093474387
49.01041492738445
40.46819132006822
34.964357574517365
31.40411193003394
29.08883961950816
27.572339144821747
26.569371917610482
25.897428428927448
25.439610994540992
25.120956642829366
24.893322775748786
24.72573279388676
24.59820571807398
24.497810335880732
24.416140489513502
24.34769871842124
24.288860770386073
24.237211732207697
24.191120020119126
24.149463690506032
24.111454347094874
24.07652362150328
24.044249803514337
24.014310258104167
23.986450424888826
23.960463498173404
23.93617700077588
23.91344381979905
23.892136141002034
23.872141275354984
23.853358728725958
23.83569809513466
23.81907750151465
23.80342242685789
23.788664779806144
23.77474215827951
23.761597240330016
23.749177272046946
23.737433629202133
23.726321436459465
23.715799232694746
23.705828674127247
23.696374269100204
23.687403139812087
23.678884807325915
23.67079099691379
23.66309546132732
23.65577381998

23.466056665845777
23.466056514346782
23.466056366725716
23.466056222883292
23.4660560827228
23.46605594615002
23.466055813073076
23.466055683402537
23.46605555705116
23.46605543393402
23.46605531396828
23.466055197073334
23.466055083170534
23.466054972183343
23.466054864037062
23.466054758659013
23.466054655978358
23.466054555925986
23.466054458434673
23.46605436343885
23.46605427087461
23.466054180679766
23.46605409279365
23.466054007157148
23.466053923712686
23.46605384240415
23.466053763176895
23.46605368597759
23.466053610754383
23.466053537456645
23.466053466035124
23.466053396441776
23.46605332862983
23.46605326255367
23.466053198168837
23.466053135432087
23.46605307430118
23.466053014735095
23.466052956693673
23.466052900137974
23.466052845029903
23.466052791332487
23.466052739009495
23.46605268802588
23.466052638347254
23.466052589940247
23.46605254277238
23.46605249681182
23.4660524520277
23.466052408389956
23.4660523658692
23.466052324436838
23.466052284065
23.46605224472662

[-0.9998981465247175,
 0.7402110726033472,
 0.010551047158168594,
 0.8182039915796901,
 -2.170763322550048,
 2.354099039931204,
 0.12121255577464878,
 -3.030498146435137,
 2.5679606475697287,
 -1.731314960041768,
 -2.249108153082881,
 0.5968035143883541,
 -4.323455645823938,
 22.60949868073878]

In [6]:
test_data

array([[ 2.71887193, -0.49042688,  0.96425328, ...,  0.78816582,
        -1.55922624,  1.00848766],
       [-0.39679863, -0.49042688,  0.36404766, ..., -1.15574859,
         0.45032651, -0.90051604],
       [-0.4059786 , -0.49042688,  0.07830384, ...,  1.15843524,
         0.45032651, -0.5120801 ],
       ...,
       [-0.40301108,  2.08605624, -1.39205635, ..., -0.09122402,
         0.40093342, -0.69040122],
       [-0.39659658, -0.49042688, -0.405594  , ...,  1.11215156,
         0.35078378,  0.1804694 ],
       [-0.14369589, -0.49042688,  1.17676627, ..., -1.75743638,
        -2.88149098,  0.46384794]])

In [7]:
def predict(x,m):
    y = []
    for el in x:
        y_pred = 0
        for j in range(len(el)):
            y_pred += m[j] * el[j]
        y.append(y_pred + m[-1])
    return np.array(y, dtype = float)
print(m)

[-0.9998981465247175, 0.7402110726033472, 0.010551047158168594, 0.8182039915796901, -2.170763322550048, 2.354099039931204, 0.12121255577464878, -3.030498146435137, 2.5679606475697287, -1.731314960041768, -2.249108153082881, 0.5968035143883541, -4.323455645823938, 22.60949868073878]


In [8]:
test_y_predicted = predict(test_data,m)
print(test_y_predicted)

[12.43300339 29.0325182  22.37180446 24.47685042 20.60340796  2.72586335
 30.39837207 24.86075442 18.6577063  23.53984713 24.11392473 17.71186336
 17.44207109 21.65443105 42.31200323 23.85061406 24.47568835 27.53993513
 20.23686914 31.15273452 23.78423703 25.00941748 33.95745088 36.43472047
 32.04171331 16.71247721 23.47216178 32.9400461  25.1795306  33.71017572
 16.88627027 26.02870045 23.27070037 25.47738095 15.00941891 29.58628687
 26.24822296 20.37402302 24.43570382  9.44718053  8.38037097 29.01350578
 29.59138904 19.7581361  20.37154161  3.14408971 39.52407296 25.71742526
 30.37537432 16.79426328 17.89048922 41.02381623 17.57212215 20.89788772
 15.59877319 21.41307552 18.45433602 23.1558566  13.67287658 17.23533635
 15.02749715 29.15133113 25.17296734 25.497446   17.21131414 17.42916168
 34.70353389 17.0130948  27.10619787 22.54636521 29.25480363 27.10993798
 17.73413189  5.74671498 36.87508151 25.09216867 30.14950746 27.23986485
 16.25195788 32.63634327 19.27311328 22.65575495 22

In [9]:
np.savetxt('predictions.csv', test_y_predicted, delimiter=',', fmt='%.30f')