In [1]:
import numpy as np

In [2]:
train_data = np.genfromtxt('training_ccpp_x_y_train.csv', delimiter = ',')

In [3]:
X_train = train_data[:,:-1]
Y_train = train_data[:,-1]
X_train, Y_train

(array([[   8.58,   38.38, 1021.03,   84.37],
        [  21.79,   58.2 , 1017.21,   66.74],
        [  16.64,   48.92, 1011.55,   78.76],
        ...,
        [  29.8 ,   69.34, 1009.36,   64.74],
        [  16.37,   54.3 , 1017.94,   63.63],
        [  30.11,   62.04, 1010.69,   47.96]]),
 array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42]))

In [4]:
from sklearn import preprocessing
sc = preprocessing.StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_train

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00,
         7.58624590e-01],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01,
        -4.46921842e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01,
         3.75010552e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01,
        -5.83682640e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01,
        -6.59584883e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01,
        -1.73110573e+00]])

In [5]:
X_test = np.genfromtxt('test_ccpp_x_test.csv', delimiter = ',')
X_test = sc.transform(X_test)
X_test

array([[-1.02742256, -0.96138014,  0.72378329,  1.20446479],
       [-1.01136848, -1.25783726, -0.09942787,  0.57331371],
       [ 0.97398614,  1.62360048, -1.27807846,  0.39005424],
       ...,
       [ 0.62748557,  0.93814142, -0.69965107,  1.27284519],
       [ 0.51644485, -0.90099073,  0.11685368, -0.54470581],
       [ 0.28499852,  0.46914312,  0.95515424,  0.80580707]])

In [6]:
def cost(x,y,m):
    final_cost = 0
    r = x.shape[0]
    c = x.shape[1]
    for i in range(r):
        ypred = 0
        for j in range(c):
            ypred += m[j] * x[i][j]
        final_cost += (1/r) * ((y[i] - ypred) ** 2)
    print(final_cost)
    
def gradientStep(x,y,coeff,alpha):
    rows = x.shape[0]
    features = x.shape[1]
    slope = [0 for i in range(features)]
    for i in range(rows):
        m_x = 0
        for j in range(features):
            m_x += coeff[j] * x[i,j]
        for j in range(features):
            slope[j] += (-2/rows) * (y[i] - m_x) * x[i][j]
    for j in range(features):
        coeff[j] -= alpha * slope[j]
    
def gradientDescent(x,y,alpha,itr):
    x = np.append(x, np.ones((x.shape[0], 1)), axis = 1)
    rows = x.shape[0]
    features = x.shape[1]
    coeff = [0 for i in range(features)]
    for _itr in range(itr):
        gradientStep(x,y,coeff,alpha)
        cost(x,y,coeff)
    return coeff

In [12]:
m = gradientDescent(X_train,Y_train,0.3,500)

33132.21953179566
5330.691245632919
878.1370186376575
164.00075579574505
48.77176340754662
29.65068368371429
26.045850829711764
25.010445392961866
24.449645234436435
24.01553357491817
23.64421809696365
23.319470785614737
23.033939558161556
22.78249365351994
22.560932401695393
22.36565198427844
22.19351276995337
22.041762587135874
21.907982018862437
21.790041177395626
21.686063721684313
21.594396073693506
21.513580700153543
21.442332747214145
21.37951952698106
21.324142471321274
21.275321239604846
21.23227971578552
21.19433366680454
21.16087986367849
21.131386491221065
21.105384693441952
21.082461119995845
21.062251355087312
21.044434124325715
21.02872618741646
21.01487783548684
21.00266892146502
20.99190536040328
20.9824160441113
20.97405012105173
20.966674598254723
20.960172227130588
20.954439639570428
20.949385704704607
20.944930080196396
20.941001935041047
20.937538823566605
20.934485692734867
20.931794006964914
20.92942097656332
20.9273288774965
20.925484451693066
20.92385837834001

20.91174899030885
20.91174899030884
20.9117489903089
20.911748990308922
20.911748990308872
20.91174899030891
20.911748990308922
20.911748990308908
20.911748990308965
20.91174899030897
20.91174899030894
20.91174899030895
20.911748990308933
20.91174899030896
20.911748990308972
20.911748990308947
20.911748990308897
20.911748990308883
20.911748990308862
20.911748990308837
20.911748990308812
20.911748990308826
20.911748990308812
20.91174899030884
20.911748990308823
20.911748990308833
20.911748990308844
20.911748990308848
20.911748990308855
20.91174899030886
20.911748990308855
20.911748990308876
20.91174899030887
20.91174899030887
20.91174899030885
20.911748990308862
20.911748990308837
20.911748990308848
20.91174899030884
20.91174899030884
20.91174899030884
20.911748990308844
20.911748990308833
20.91174899030884
20.91174899030884
20.911748990308855
20.911748990308844
20.91174899030884
20.911748990308844
20.911748990308826
20.91174899030883
20.911748990308812
20.91174899030882
20.911748990308

In [18]:
def predict(x,m):
    y = []
    for el in x:
        y_pred = 0
        for j in range(len(el)):
            y_pred += m[j] * el[j]
        y.append(y_pred + m[-1])
    return np.array(y, dtype = float)
print(m)

[-14.902729354766294, -2.894278186953888, 0.34973996139212143, -2.3423017175716065, 454.43129319955403]


In [19]:
test_y_predicted = predict(X_test,m)
print(test_y_predicted)

[469.95711113 471.76632733 433.85647002 ... 439.13871988 450.65930697
 447.27281902]


In [20]:
np.savetxt('predictions.csv', test_y_predicted, delimiter=',', fmt='%.28f')