In [2]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [3]:
print(type(b))

<class 'numpy.ndarray'>


In [5]:
c = np.array(a * 5)
c

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [10]:
d = np.ones(5, dtype = int)
d

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [12]:
e = np.zeros(5, dtype = int)
e

array([0, 0, 0, 0, 0])

In [13]:
f = np.zeros((3,3), dtype = int)
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
g = np.full((2,2), 100, dtype = int)
g

array([[100, 100],
       [100, 100]])

In [16]:
h = np.empty((2,2))
h
# np.empty gives random values, but creates an array

array([[1.21614546e-311, 9.34579233e-307],
       [1.33511562e-306, 1.78020848e-306]])

In [17]:
m =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
n = np.array(m)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1]:
import numpy as np
a = np.zeros(10, dtype = int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [4]:
b = np.arange(100)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
b = np.arange(1, 11, 2, float)
b

array([1., 3., 5., 7., 9.])

In [6]:
b = np.linspace(2,10, 20)
b

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])