In [1]:
import numpy as np

In [2]:
train_data = np.genfromtxt('train.csv', delimiter = ',')
print(train_data)
print(train_data.shape)

[[-4.91050164e-02 -4.46416365e-02  1.60854917e-01 ...  2.80165065e-02
   1.13486232e-02  3.46000000e+02]
 [-7.09002471e-02  5.06801187e-02 -8.91974838e-02 ... -1.29079423e-02
  -5.49250874e-02  1.04000000e+02]
 [ 1.75052192e-03 -4.46416365e-02 -7.08746786e-02 ... -2.25121719e-02
   7.20651633e-03  4.90000000e+01]
 ...
 [ 2.35457526e-02 -4.46416365e-02  7.03187031e-02 ... -1.91970476e-02
  -9.36191133e-03  2.88000000e+02]
 [ 1.62806757e-02  5.06801187e-02  7.24743273e-02 ... -2.36445576e-02
   6.10539062e-02  1.31000000e+02]
 [-9.14709343e-03  5.06801187e-02 -3.09956318e-02 ...  6.20931562e-03
   2.79170509e-02  4.20000000e+01]]
(331, 11)


In [3]:
Y = train_data[:, -1]
Y

array([346., 104.,  49., 180., 110.,  72.,  68., 216.,  47., 296.,  65.,
        96.,  67.,  52., 100., 202., 128.,  63., 281., 152., 124., 245.,
       101., 113.,  48., 197., 186., 132., 245.,  91.,  43., 101., 111.,
       199., 220., 281., 217.,  93., 174., 150., 206.,  61.,  55., 118.,
        53., 275., 215., 142.,  90.,  65., 200.,  96., 249., 200., 155.,
       170., 141., 179., 225.,  61., 103., 131., 158., 275., 246.,  97.,
       302.,  91., 178.,  51., 170., 104., 168., 257., 182.,  71., 220.,
       241., 192., 220., 220., 141.,  89., 144., 150., 135., 200.,  39.,
        25., 185.,  52.,  92.,  63., 152.,  69.,  68., 274., 279., 236.,
       168., 143., 135., 123., 277.,  60.,  72.,  72., 109.,  86.,  92.,
        99.,  48., 170., 283., 129.,  75., 270., 272.,  31., 262., 232.,
       191., 140., 233., 196., 263.,  88.,  84., 137., 128.,  78., 140.,
       252.,  55., 104., 235.,  37., 122.,  72., 144., 138., 253.,  90.,
        53., 198., 145.,  73., 252.,  77., 295., 24

In [4]:
X = train_data[:, :-1]
X

array([[-0.04910502, -0.04464164,  0.16085492, ...,  0.03430886,
         0.02801651,  0.01134862],
       [-0.07090025,  0.05068012, -0.08919748, ..., -0.00259226,
        -0.01290794, -0.05492509],
       [ 0.00175052, -0.04464164, -0.07087468, ..., -0.03949338,
        -0.02251217,  0.00720652],
       ...,
       [ 0.02354575, -0.04464164,  0.0703187 , ..., -0.00259226,
        -0.01919705, -0.00936191],
       [ 0.01628068,  0.05068012,  0.07247433, ..., -0.00259226,
        -0.02364456,  0.06105391],
       [-0.00914709,  0.05068012, -0.03099563, ..., -0.00259226,
         0.00620932,  0.02791705]])

In [5]:
X.shape, Y.shape

((331, 10), (331,))

In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [7]:
model.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
def score(ypred, ytrue):
    u = ((ytrue - ypred) ** 2).sum()
    v = ((ytrue - ytrue.mean()) ** 2).sum()
    return 1 - u/v

In [9]:
Y_train_predicted = model.predict(X)
score(Y_train_predicted, Y)

0.4957208055805604

In [10]:
X_Test_Set = np.genfromtxt('test.csv', delimiter = ',')
X_Test_Set.shape

(111, 10)

In [11]:
Y_Test_predict = model.predict(X_Test_Set)
Y_Test_predict

array([105.52974799, 105.8039198 , 178.60857225,  79.3828781 ,
        52.95868706,  98.87263854, 150.71755448,  34.86515216,
       113.13535727, 161.50184038, 135.8615611 ,  94.71592222,
       138.48094422, 141.37441723, 158.76862662, 171.65288616,
       106.44835654, 103.92659639,  95.38693889, 167.40118092,
       166.53426278, 101.53464712, 252.45035972, 147.02258547,
       214.78906632, 161.27557106, 210.61315228,  71.78091585,
       189.65032431, 206.6134259 , 219.98643455, 168.80192534,
       116.84846127, 178.74399639,  77.03247418,  59.54633214,
       111.5673781 , 156.95186739, 154.59591259, 198.94457493,
       115.53884017, 153.46699024,  84.96179518, 113.70337192,
       142.14155617, 147.31040378,  82.78072358,  77.89237327,
       128.99006192, 261.58712282, 213.31187775, 243.98791257,
       167.68132094, 183.69712124, 166.85926884, 202.11440188,
       220.39235543, 172.40288024, 176.60897931, 109.04656567,
       276.37789836,  90.99941821, 289.37221147, 119.56

In [12]:
Y_Test_predict.shape

(111,)

In [13]:
np.savetxt('predictions.csv', Y_Test_predict, fmt = '%.5f', delimiter = ',')