In [1]:
import numpy as np

In [2]:
train_data = np.genfromtxt('train.csv', delimiter = ',')
print(train_data)
print(train_data.shape)

[[-4.91050164e-02 -4.46416365e-02  1.60854917e-01 ...  2.80165065e-02
   1.13486232e-02  3.46000000e+02]
 [-7.09002471e-02  5.06801187e-02 -8.91974838e-02 ... -1.29079423e-02
  -5.49250874e-02  1.04000000e+02]
 [ 1.75052192e-03 -4.46416365e-02 -7.08746786e-02 ... -2.25121719e-02
   7.20651633e-03  4.90000000e+01]
 ...
 [ 2.35457526e-02 -4.46416365e-02  7.03187031e-02 ... -1.91970476e-02
  -9.36191133e-03  2.88000000e+02]
 [ 1.62806757e-02  5.06801187e-02  7.24743273e-02 ... -2.36445576e-02
   6.10539062e-02  1.31000000e+02]
 [-9.14709343e-03  5.06801187e-02 -3.09956318e-02 ...  6.20931562e-03
   2.79170509e-02  4.20000000e+01]]
(331, 11)


In [3]:
Y = train_data[:, -1]
Y

array([346., 104.,  49., 180., 110.,  72.,  68., 216.,  47., 296.,  65.,
        96.,  67.,  52., 100., 202., 128.,  63., 281., 152., 124., 245.,
       101., 113.,  48., 197., 186., 132., 245.,  91.,  43., 101., 111.,
       199., 220., 281., 217.,  93., 174., 150., 206.,  61.,  55., 118.,
        53., 275., 215., 142.,  90.,  65., 200.,  96., 249., 200., 155.,
       170., 141., 179., 225.,  61., 103., 131., 158., 275., 246.,  97.,
       302.,  91., 178.,  51., 170., 104., 168., 257., 182.,  71., 220.,
       241., 192., 220., 220., 141.,  89., 144., 150., 135., 200.,  39.,
        25., 185.,  52.,  92.,  63., 152.,  69.,  68., 274., 279., 236.,
       168., 143., 135., 123., 277.,  60.,  72.,  72., 109.,  86.,  92.,
        99.,  48., 170., 283., 129.,  75., 270., 272.,  31., 262., 232.,
       191., 140., 233., 196., 263.,  88.,  84., 137., 128.,  78., 140.,
       252.,  55., 104., 235.,  37., 122.,  72., 144., 138., 253.,  90.,
        53., 198., 145.,  73., 252.,  77., 295., 24

In [4]:
X = train_data[:, :-1]
X

array([[-0.04910502, -0.04464164,  0.16085492, ...,  0.03430886,
         0.02801651,  0.01134862],
       [-0.07090025,  0.05068012, -0.08919748, ..., -0.00259226,
        -0.01290794, -0.05492509],
       [ 0.00175052, -0.04464164, -0.07087468, ..., -0.03949338,
        -0.02251217,  0.00720652],
       ...,
       [ 0.02354575, -0.04464164,  0.0703187 , ..., -0.00259226,
        -0.01919705, -0.00936191],
       [ 0.01628068,  0.05068012,  0.07247433, ..., -0.00259226,
        -0.02364456,  0.06105391],
       [-0.00914709,  0.05068012, -0.03099563, ..., -0.00259226,
         0.00620932,  0.02791705]])

In [5]:
X.shape, Y.shape

((331, 10), (331,))

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size = 0.3)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((231, 10), (100, 10), (231,), (100,))

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [8]:
model.fit(X_train, Y_train)
ypred = model.predict(X_test)

In [9]:
ypred

array([127.06368051, 237.85432869, 217.02147811, 191.05229379,
       144.52538434, 187.10897933, 193.66386024,  44.70358276,
       131.56493835, 141.37524387, 218.42424434, 141.88950793,
       133.05814211, 166.64402835, 176.64666867, 268.89574551,
       148.35497621,  99.13330652,  98.15461777, 134.76511604,
       133.25835687, 142.51462397, 266.59947664,  90.03479208,
       193.71388811, 166.83875318, 174.49600557, 155.75270782,
       150.5031959 ,  58.22342039, 157.54583914,  54.65154231,
        70.55315037,  83.82990636, 107.70892394, 175.24856728,
       127.66299569, 167.10728461, 163.33175869,  67.39742305,
       193.03037643, 176.21989978, 213.96326644, 282.50710412,
       155.71625252, 165.44029258, 122.03612891,  92.69069316,
        74.22243334, 180.95502604, 188.44592582,  63.58368976,
       139.91502839,  64.36719368, 149.16107427, 197.49304271,
       212.86889669, 156.84677013, 163.75356302, 196.18534444,
       116.21179689, 126.45826427, 262.97022085, 220.42

In [10]:
def score(ypred, ytrue):
    u = ((ytrue - ypred) ** 2).sum()
    v = ((ytrue - ytrue.mean()) ** 2).sum()
    return 1 - u/v

In [11]:
score(ypred, Y_test)

0.5423995884220285

In [12]:
Y_train_predicted = model.predict(X_train)
score(Y_train_predicted, Y_train)

0.4515730891136176

In [13]:
X_Test_Set = np.genfromtxt('test.csv', delimiter = ',')
X_Test_Set.shape

(111, 10)

In [14]:
Y_Test_predict = model.predict(X_Test_Set)
Y_Test_predict

array([106.79269629, 113.19686288, 190.76127896,  76.91495686,
        63.78985639, 115.02589802, 155.89066064,  32.02017906,
       112.59619233, 174.11526804, 149.94249297, 105.44784715,
       148.44920492, 151.61853164, 176.93037013, 164.44414294,
       103.59017899, 104.47156543,  78.16811291, 172.60890188,
       169.44177498, 108.47891115, 240.74337083, 147.89866731,
       227.09279361, 160.0403586 , 222.0893206 ,  82.55505562,
       204.21944723, 210.18573831, 216.70041204, 171.35377939,
       115.54017107, 186.69541985,  87.61255067,  65.5469573 ,
       110.33096462, 158.76141693, 160.92159974, 190.11760911,
       107.03886505, 162.81743114,  94.04500776, 116.72004474,
       136.24003969, 156.03603632,  89.06771456,  80.19300168,
       134.40930661, 249.91765629, 200.27404763, 243.15954033,
       176.52636181, 189.6272483 , 181.88047505, 194.5780843 ,
       224.11236804, 172.16721531, 179.66052413, 107.9890359 ,
       284.59408559,  93.34339338, 277.84297725, 126.24

In [15]:
Y_Test_predict.shape

(111,)

In [16]:
np.savetxt('predictions.csv', Y_Test_predict, fmt = '%.5f', delimiter = ',')